In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
naver_raw = requests.get("https://www.naver.com")
soup = BeautifulSoup(naver_raw.text, "html.parser")

In [3]:
css_soup = soup.select("#NM_FAVORITE > div.group_nav > ul.list_nav.type_fix")
css_list = css_soup[0].find_all("a")
for i in css_list:
    print(i.text)

메일
카페
블로그
지식iN
쇼핑
쇼핑LIVE
Pay
TV

In [248]:
url = "https://search.naver.com/search.naver?where=view&sm=tab_jum&query=%EC%84%A0%EB%A6%89%EC%97%AD+%EB%A7%9B%EC%A7%91"

html = requests.get(url)
soup = BeautifulSoup(html.text, "html.parser")

soup_ul = soup.select("#main_pack > section > div > div._list > panel-list > div:nth-child(1) > more-contents > div > ul")
soup_ul[0].find_all("a")[2]

<a class="spnew_af item item_quick" href="https://keep.naver.com/" onclick="return goOtherCR(this,'a=rvw*f.kephome&amp;r=1&amp;i=90000003_0000000000000033E815F67A&amp;u='+urlencode(this.href));" target="_blank">Keep 바로가기</a>

In [ ]:
soup_ul[0]

In [42]:
# 실습 
# select 를 이용해 naver 지식인에서 선릉역 맛집을 입력한 결과를 
# 제목, 등록일, 요약 순으로 dataframe에 저장하세요

# 추가실습: 검색어를 입력받고 출력하도록 해보세요 
# 1시 20분에 진행

In [250]:
user_value = input("검색어를 입력하세요")
# 방법1 
user_input = user_value.replace(" ", "+")

# 방법2
#from urllib import parse
#user_input = parse.quote(user_value)

In [251]:
# url = "https://kin.naver.com/search/list.naver?query={%EC%84%A0%EB%A6%89%EC%97%AD+%EB%A7%9B%EC%A7%91}"
# url = "https://kin.naver.com/search/list.naver?query=역삼역+맛집"
url = f"https://kin.naver.com/search/list.naver?query={user_input}"
html = requests.get(url)
soup = BeautifulSoup(html.text, "html.parser")

In [253]:
li_soup = ul_soup[0].find_all("li")

AttributeError: 'str' object has no attribute 'find_all'

In [254]:
user_value = input("검색어를 입력하세요")
user_input = user_value.replace(" ", "+")# 역삼동 맛집과 역삼동맛집의 검색결과가 다르므로 이러한 차이를없애기위해서 다음과 같이 함수 사용

url = f"https://kin.naver.com/search/list.naver?query={user_input}"
html = requests.get(url)
soup = BeautifulSoup(html.text, "html.parser")




ul_soup = soup.select("#s_content > div.section > ul") # 검색을 위해 큰 조각으로 하나선택
li_soup = ul_soup[0].find_all("li")   # 필요한정보들이 구분되어 있는 묶음이 하나의 리스트로 지정될 수 있는조각 확보(이후에 반복문 사용을 위해)

kin = []
for i in li_soup:
    title = i.find("dt").text.replace("\n", " ")
    date = i.find_all("dd")[0].text
    cont = i.find_all("dd")[1].text
    kin.append({"제목": title, "날짜":date, "내용":cont})

In [14]:
!pip install pandas

Collecting pandas
  Using cached pandas-1.5.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
Requirement already satisfied: python-dateutil>=2.8.1 in /mnt/c/Users/student/Desktop/lab/webcrawling/lib/python3.10/site-packages (from pandas) (2.8.2)
Collecting numpy>=1.21.0
  Using cached numpy-1.23.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Collecting pytz>=2020.1
  Using cached pytz-2022.6-py2.py3-none-any.whl (498 kB)
Requirement already satisfied: six>=1.5 in /mnt/c/Users/student/Desktop/lab/webcrawling/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: pytz, numpy, pandas
Successfully installed numpy-1.23.5 pandas-1.5.2 pytz-2022.6

In [21]:
import pandas as pd

In [24]:
pd.DataFrame(kin)

,제목,날짜,내용
0,손흥민선수 아버지께서 은퇴할때까지 연,2022.11.26.,... 손흥민 아버지가 말린다고 열애를 안하진 않아요. 대신 축구에 대한 열정이나 ...
1,손흥민 아버지는 왜 손흥민거리 만들기,2022.07.13.,손흥민 아버지는 왜 손흥민거리 만들기 반대할까요? 아버지 말로는 흥민이가 은퇴하면 ...
2,손흥민이 토트넘에 의해 방출 된다는...,2022.08.27.,아버지가 토트넘이 손흥민이 방출 시킨다고 얘기를 하는데 이게 맞나요? 아버지가 토트...
3,손흥민 아버지도 독일에서 살았나요?,2020.12.26.,손흥민 선수가 영어와 독일어를 잘 하잖아요.손흥민 아버지도 독일에서 살았나요? 손흥...
4,손흥민 독일에서 잘했을때 아버지반응 궁금,2022.06.23.,... 손흥민 아버지는 현재도 아들이 월드클래스가 아니라 계속해서 노력해야 한다고 ...
5,손흥민이랑 결혼하고시퍼요..,2022.11.29.,손흥민이랑 결혼할수있는 방법없나요… 아니면 만날수있는방법 이라던지… 그냥 아무방법 ...
6,손흥민과 결혼하는법 내공 200,2022.12.08.,손흥민오빠랑 결혼하고싶어요 손흥민 아버지 찾아가세요
7,손흥민아버지이름은?,2019.06.24.,손흥민아버지이름은? 손흥민 아버지의 이름은 손웅정입니다.
8,손흥민 아버지는,2022.11.24.,son이 son이야ㅋㅋㅋㅋㅋㅋ son이지요
9,손흥민 아버지도 영국 리그에서 뛰었나요?,2020.12.22.,손흥민 아버지도 영국 프리미어리그에서 뛰었나요? 손웅정 씨는 k리그에서만 뛰었습니다.

In [ ]:
#나의 실패작
url = "https://kin.naver.com/search/list.naver?query=%EC%84%A0%EB%A6%89%EC%97%AD+%EB%A7%9B%EC%A7%91"
naver_raw = requests.get(url)
soup = BeautifulSoup(naver_raw.text,"html.parser")
naver_list = soup.select("#s_content > div.section > ul > li:nth-of-type(1) > dl > dt > a")
naver_time = soup.select("#s_content > div.section > ul > li:nth-of-type(1) > dl > dd.txt_inline")
naver_content = soup.select("#s_content > div.section > ul > li > dl > dd")

A = range(len(naver_list))
B = range(len(naver_time))
C = range(len(naver_content))

for i,j,z in zip(A,B,C):
            print(naver_list[i].text)
            print("\n")      
            print(naver_time[j].text)
            print("\n")
            print(naver_content[z+1].text)

In [14]:
# 추가

In [ ]:
# 혹시 select로 반복문은 어떻게 굴려야할지 여쭤봐도 될까요
# li: nth-child (1 ) 이
# 게시물 순서에따라서 바뀌는데
# find를 안쓰고 select를 쓰려니
# 못하겠어서요
# (f'#s_content > div.section > ul > li:nth-child({j+1}) > dl > dt > a')
# 이런 식으로 이중반복문 써보려 했는데

In [25]:
for i in range(1,10):
    ul_soup = soup.select(f"#s_content > div.section > ul > li:nth-child({i}) > dl > dt > a")[0].text
    print(ul_soup)

손흥민선수 아버지께서 은퇴할때까지 연
손흥민 아버지는 왜 손흥민거리 만들기
손흥민이 토트넘에 의해 방출 된다는...
손흥민 아버지도 독일에서 살았나요?
손흥민 독일에서 잘했을때 아버지반응 궁금
손흥민이랑 결혼하고시퍼요..
손흥민과 결혼하는법 내공 200
손흥민아버지이름은?
손흥민 아버지는

In [ ]:
#s_content > div.section > ul > li:nth-child(2) > dl > dt > a

In [ ]:
#일자별 차트 크롤링 
# 1등 가져오기
#전체 순위가져오기

In [ ]:
# 순위에 따라서 점수 부여
# 1등 ->100점 , 100등 ->1점

In [ ]:
#특정 기간내에 차트 진입 점수 계산
#예) 15일간 차트 분석 총 합산 점수 계산 
# 12월 12일 ->아이유 150점 , 12월 11일 -> 아이유 160점 , 12월 1일 아이유 누적점수 ~~점
# 누적된 점수별 아티스트 계산 상위 10명을 히스토그램으로 그려보세요.

In [164]:
import numpy as np

In [171]:
score =

'100'

In [ ]:
soup_bugs

In [201]:
bugs_url = "https://music.bugs.co.kr/chart/track/day/total?chartdate="
bugs_url = bugs_url + str(20221211)   #일자별차트 순위를 보기 위해서 날짜를 따로 빼서 지정해줌
bugs_raw = requests.get(bugs_url)
soup_bugs = BeautifulSoup(bugs_raw.text,"html.parser")      #순서 1(서버 url받고 bs로 필요한 정보 꺼내옴)



bugs_title = soup_bugs.select("#CHARTday > table")[0].find_all("p",{"class":"title"})
bugs_rank = soup_bugs.select("#CHARTday > table")[0].find_all("div",{"class":"ranking"})
bugs_artist = soup_bugs.find_all("tbody")[0].find_all("p",{"class":"artist"})       #순서2
#CHARTday > table > tbody > tr:nth-child(1) > td:nth-child(4) > div > strong
Chart = []
num = 101
for i,j,z in zip(bugs_title,bugs_rank,bugs_artist):      #순서3
        title = i.text.replace("\n","")
        rank = j.find_all("strong")[0].text.replace("\n","")
        artist = z.text.replace("\n","")
        score = num-int(rank)
        Chart.append({"제목": title, "순위":rank, "가수":artist,"점수":score})    #순서4



bugs_Data = pd.DataFrame(Chart) 
bugs_Data.groupby("가수").sum().sort_values("점수",ascending=False)

/tmp/ipykernel_511/2793866880.py:24: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  bugs_Data.groupby("가수").sum().sort_values("점수",ascending=False)

                                          점수
가수
NewJeans                                 272
IVE (아이브)                                265
카라(Kara)                                 246
LE SSERAFIM (르세라핌)                       222
Charlie Puth(찰리 푸스)                      207
...                                      ...
케이시                                        7
Kelly Clarkson(켈리 클락슨)                     6
릴러말즈 (Leellamarz)\r릴러말즈 (Leellamarz)\r     5
싸이 (PSY)                                   4
Wham!(왬)                                   3

[73 rows x 1 columns]

In [207]:
df = pd.DataFrame(bugs_Data,columns= ["순위","제목","가수","점수"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순위      100 non-null    object
 1   제목      100 non-null    object
 2   가수      100 non-null    object
 3   점수      100 non-null    int64
dtypes: int64(1), object(3)
memory usage: 3.2+ KB

In [210]:
!pip install tqdm

Collecting tqdm
  Downloading tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 KB 2.2 MB/s eta 0:00:00
Installing collected packages: tqdm
Successfully installed tqdm-4.64.1

In [214]:
from tqdm import tqdm
sdt = input("시작입 입력 : ")     #특정기간내 차트 진입 점수를 계산해야하므로 특정기간을 만들어준다.
edt = input("종료일 입력 : ")

dates = pd.date_range(sdt,edt)  # 시작전과 끝 날짜를 지정하면 그기간을 갖는 시계열 데이터로 변환해주는 함수
dates = [i.strftime("%Y%m%d") for i in dates] #문자열로 변환하여 변수안에 넣음

df_bugs = pd.DataFrame() # 후에 나온 결과값을 넣어줄 임의의 빈 데이터 프레임 만들어 놓기

for date in tqdm(dates):
       url="https://music.bugs.co.kr/chart/track/day/total?chartdate=" + str(date)

       html=requests.get(url)
       soup = BeautifulSoup(html.text,"html.parser")
       
       bugs_day = [] #데이터 프레임으로 만들기 위해 append함수를 이용해줄 빈 리스트를 가진 변수를 하나 생성
       tbody= soup.find("tbody")
       tr_soup = tbody.find_all("tr")

       scr=101   #점수의 초기값
       for tr in tr_soup:
              rank = tr.find("div",class_="ranking").get_text().split("\n")[1]
              title = tr.find("p",class_="title").get_text().replace("\n","")
              art= tr.find("p",class_="artist").get_text().replace("\n","")
              album=tr.find("a",class_="album").get_text().replace("\n","")
              scr -= 1  # 1회 추출시 -1만큼 감소 
              bugs_day.append([date,rank,title,art,album,scr])
       
       # bugs_day
       df = pd.DataFrame(bugs_day,columns=["날짜","순위","곡명","아티스트","앨범","점수"])
       df_bugs = pd.concat([df_bugs,df]) #그날 그날의 데이터로 만든 데이터프레임을 빈 데이터프레임에 합쳐줌 for문으로 받고있으므로, 빈데이터에 합치는 작업을 지속해서 반복함


df_bugs.reset_index(drop=True,inplace=True) #인덱스를 리셋해주지 않으면 인덱스가 계속 0~99로반복된다 실제로는 하루당 100곡씩 100*n일만큼 인덱스가 형성되어야 하므로 본 함수를
#사용하여 이를 만들어준다.
#df_bugs.info()

100%|██████████| 32/32 [00:15<00:00,  2.08it/s]

In [215]:
df_bugs

,날짜,순위,곡명,아티스트,앨범,점수
0,20221110,1,사건의 지평선,윤하(Younha/ユンナ),YOUNHA 6th Album Repackage 'END THEORY : Final...,100
1,20221110,2,ANTIFRAGILE,LE SSERAFIM (르세라핌),ANTIFRAGILE,99
2,20221110,3,Nxde,(여자)아이들,I love,98
3,20221110,4,Hype Boy,NewJeans,NewJeans 1st EP 'New Jeans',97
4,20221110,5,After LIKE,IVE (아이브),After LIKE,96
...,...,...,...,...,...,...
3195,20221211,96,아저씨,릴러말즈 (Leellamarz)\r릴러말즈 (Leellamarz)\r,쇼미더머니 11 Episode 1,5
3196,20221211,97,That That (prod. & feat. SUGA of BTS),싸이 (PSY),싸다9,4
3197,20221211,98,Last Christmas,Wham!(왬),LAST CHRISTMAS,3
3198,20221211,99,MY BAG,(여자)아이들,I NEVER DIE,2
3199,20221211,100,가을밤에 든 생각,잔나비,잔나비 소곡집 l,1

In [216]:
df_bugs_top = df_bugs.groupby(["아티스트"]).sum().sort_values("점수",ascending=False).head(10)

/tmp/ipykernel_511/3280847816.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_bugs_top = df_bugs.groupby(["아티스트"]).sum().sort_values("점수",ascending=False).head(10)

In [217]:
df_bugs_top

                         점수
아티스트
NewJeans               8592
IVE (아이브)              8175
LE SSERAFIM (르세라핌)     6841
Charlie Puth(찰리 푸스)    6349
윤하(Younha/ユンナ)         6264
(여자)아이들                5692
SECRET NUMBER (시크릿넘버)  5566
BLACKPINK              5399
Red Velvet (레드벨벳)      4540
BE'O (비오)              3990

In [208]:
df_bugs=pd.DataFrame()

In [ ]:
import matplotlib.pyplot as plt
import platform

plt.style.use('ggplot')
plt.figure(figsize=(10,4))
plt.xticks(size=9,rotation=45)
plt.bar(df_bugs_top.index,df_bugs_top["점수"])
plt.title(f"12월 가장 많이 나타난 아티스트(기간:{sdt}~{edt})",size=15)
plt.ylabel("점수")

In [236]:
df_bugs_values = df_bugs.groupby(["아티스트","날짜"]).sum().sort_values("점수", ascending=False)

/tmp/ipykernel_511/886951807.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_bugs_values = df_bugs.groupby(["아티스트","날짜"]).sum().sort_values("점수", ascending=False)

In [237]:
df_bugs_top.index

Index(['NewJeans', 'IVE (아이브)', 'LE SSERAFIM (르세라핌)', 'Charlie Puth(찰리 푸스)',
       '윤하(Younha/ユンナ)', '(여자)아이들', 'SECRET NUMBER (시크릿넘버)', 'BLACKPINK',
       'Red Velvet (레드벨벳)', 'BE'O (비오)'],
      dtype='object', name='아티스트')

In [238]:
df_bugs_values_top = df_bugs_values.loc[df_bugs_top.index]

In [241]:
df_bugs_values_top = df_bugs_values_top.reset_index()

In [242]:
df_bugs_values_top

          아티스트        날짜   점수
0     NewJeans  20221113  294
1     NewJeans  20221112  291
2     NewJeans  20221110  289
3     NewJeans  20221114  285
4     NewJeans  20221115  283
..         ...       ...  ...
295  BE'O (비오)  20221128  112
296  BE'O (비오)  20221125  112
297  BE'O (비오)  20221122  110
298  BE'O (비오)  20221123  107
299  BE'O (비오)  20221124   95

[300 rows x 3 columns]

In [243]:
df_bugs_values_top_pivot = df_bugs_values_top.pivot("아티스트","날짜","점수")

/tmp/ipykernel_511/2688928874.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  df_bugs_values_top_pivot = df_bugs_values_top.pivot("아티스트","날짜","점수")

In [244]:
df_bugs_values_top_pivot.fillna(0)

날짜,20221110,20221111,20221112,20221113,20221114,20221115,20221116,20221117,20221118,20221119,...,20221202,20221203,20221204,20221205,20221206,20221207,20221208,20221209,20221210,20221211
아티스트,,,,,,,,,,,,,,,,,,,,,
(여자)아이들,238.0,217.0,213.0,224.0,190.0,202.0,192.0,182.0,194.0,178.0,...,182.0,175.0,169.0,168.0,166.0,168.0,168.0,173.0,173.0,168.0
BE'O (비오),145.0,133.0,148.0,149.0,142.0,132.0,123.0,124.0,132.0,133.0,...,128.0,122.0,120.0,125.0,127.0,121.0,123.0,125.0,121.0,120.0
BLACKPINK,179.0,171.0,184.0,180.0,174.0,176.0,169.0,169.0,169.0,173.0,...,176.0,174.0,169.0,170.0,173.0,171.0,172.0,173.0,171.0,170.0
Charlie Puth(찰리 푸스),220.0,207.0,226.0,223.0,193.0,201.0,191.0,191.0,194.0,200.0,...,207.0,202.0,203.0,196.0,203.0,205.0,205.0,205.0,208.0,207.0
IVE (아이브),265.0,257.0,271.0,266.0,256.0,259.0,247.0,255.0,255.0,263.0,...,268.0,267.0,262.0,262.0,260.0,261.0,262.0,264.0,265.0,265.0
LE SSERAFIM (르세라핌),211.0,182.0,190.0,184.0,190.0,183.0,195.0,177.0,181.0,185.0,...,228.0,225.0,230.0,229.0,228.0,222.0,229.0,220.0,213.0,222.0
NewJeans,289.0,282.0,291.0,294.0,285.0,283.0,278.0,269.0,272.0,268.0,...,272.0,271.0,265.0,266.0,269.0,267.0,267.0,270.0,274.0,272.0
Red Velvet (레드벨벳),44.0,41.0,35.0,37.0,32.0,38.0,35.0,35.0,42.0,33.0,...,294.0,237.0,244.0,235.0,223.0,212.0,196.0,169.0,143.0,160.0
SECRET NUMBER (시크릿넘버),0.0,0.0,0.0,0.0,0.0,0.0,478.0,465.0,463.0,502.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
윤하(Younha/ユンナ),131.0,115.0,121.0,160.0,167.0,155.0,271.0,257.0,249.0,251.0,...,187.0,187.0,187.0,184.0,185.0,184.0,185.0,185.0,185.0,185.0

In [246]:
import matplotlib
matplotlib.matplotlib_fname()
.

'/mnt/c/Users/student/Desktop/lab/webcrawling/lib/python3.10/site-packages/matplotlib/mpl-data/matplotlibrc'